### ISSUE TITLE
The dependency 'IQKeyboardManager' is not used in any concrete target

### ISSUE THREAD

**Issue by mikeres0** [tjvantoll/nativescript-IQKeyboardManager#2]
I receive this error upon building my iOS project. I have no idea why... 

I added the plugin using ```tns plugin add nativescript-iqkeyboardmanager```, and then attempted to build the project via. ```tns build iOS```.

**Comment by tjvantoll** [comment]
Hey @mikeres0,

Sorry you ran into issues with this. At a glance here I’m not sure what’s up. Could you run `tns build ios --log trace` so I could see the full build output?

**Comment by tjvantoll** [comment]
Full log from @mikeres0:

```
john-thornewills-imac:nextra-workplan4 johnt$ tns build ios --log trace
execFile: /usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.4.1_1/tools/android "--help"
Result when throw error is false:
{ stdout: '\n       Usage:\n       android [global options] action [action options]\n       Global options:\n  -s --silent     : Silent mode, shows errors only.\n  -v --verbose    : Verbose mode, shows errors, warnings and all messages.\n     --clear-cache: Clear the SDK Manager repository manifest cache.\n  -h --help       : Help on a specific command.\n\n                                                                    Valid\n                                                                    actions\n                                                                    are\n                                                                    composed\n                                                                    of a verb\n                                                                    and an\n                                                                    optional\n                                                                    direct\n                                                                    object:\n-    sdk              : Displays the SDK Manager window.\n-    avd              : Displays the AVD Manager window.\n-   list              : Lists existing targets or virtual devices.\n-   list avd          : Lists existing Android Virtual Devices.\n-   list target       : Lists existing targets.\n-   list device       : Lists existing devices.\n-   list sdk          : Lists remote SDK repository.\n- create avd          : Creates a new Android Virtual Device.\n-   move avd          : Moves or renames an Android Virtual Device.\n- delete avd          : Deletes an Android Virtual Device.\n- update avd          : Updates an Android Virtual Device to match the folders\n                        of a new SDK.\n- create project      : Creates a new Android project.\n- update project      : Updates an Android project (must already have an\n                        AndroidManifest.xml).\n- create test-project : Creates a new Android project for a test package.\n- update test-project : Updates the Android project for a test package (must\n                        already have an AndroidManifest.xml).\n- create lib-project  : Creates a new Android library project.\n- update lib-project  : Updates an Android library project (must already have\n                        an AndroidManifest.xml).\n- create uitest-project: Creates a new UI test project.\n- update adb          : Updates adb to support the USB devices declared in the\n                        SDK add-ons.\n- update sdk          : Updates the SDK by suggesting new platforms to install\n                        if available.\n',
  stderr: '',
  exitCode: 1 }

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.

Exec uname -a 
 stdout: Darwin john-thornewills-imac.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 2.14.9
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 7.2.1
Build version 7C1002
 
 stderr: 
Exec pod --version 
 stdout: 1.0.0.beta.3
 
 stderr: 
Exec '/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.32
Revision 09a0d98bebce-android
 
 stderr: 
spawn: /usr/local/Cellar/android-sdk/24.4.1_1/tools/android "-h"
Result when throw error is false:
{ stdout: '\n       Usage:\n       android [global options] action [action options]\n       Global options:\n  -s --silent     : Silent mode, shows errors only.\n  -v --verbose    : Verbose mode, shows errors, warnings and all messages.\n     --clear-cache: Clear the SDK Manager repository manifest cache.\n  -h --help       : Help on a specific command.\n\n                                                                    Valid\n                                                                    actions\n                                                                    are\n                                                                    composed\n                                                                    of a verb\n                                                                    and an\n                                                                    optional\n                                                                    direct\n                                                                    object:\n-    sdk              : Displays the SDK Manager window.\n-    avd              : Displays the AVD Manager window.\n-   list              : Lists existing targets or virtual devices.\n-   list avd          : Lists existing Android Virtual Devices.\n-   list target       : Lists existing targets.\n-   list device       : Lists existing devices.\n-   list sdk          : Lists remote SDK repository.\n- create avd          : Creates a new Android Virtual Device.\n-   move avd          : Moves or renames an Android Virtual Device.\n- delete avd          : Deletes an Android Virtual Device.\n- update avd          : Updates an Android Virtual Device to match the folders\n                        of a new SDK.\n- create project      : Creates a new Android project.\n- update project      : Updates an Android project (must already have an\n                        AndroidManifest.xml).\n- create test-project : Creates a new Android project for a test package.\n- update test-project : Updates the Android project for a test package (must\n                        already have an AndroidManifest.xml).\n- create lib-project  : Creates a new Android library project.\n- update lib-project  : Updates an Android library project (must already have\n                        an AndroidManifest.xml).\n- create uitest-project: Creates a new UI test project.\n- update adb          : Updates adb to support the USB devices declared in the\n                        SDK add-ons.\n- update sdk          : Updates the SDK by suggesting new platforms to install\n                        if available.\n',
  stderr: '',
  exitCode: 1 }
Exec mono --version 
 stdout:  
 stderr: /bin/sh: mono: command not found

Exec git --version 
 stdout: git version 2.5.4 (Apple Git-61)
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: /bin/sh: gradle: command not found

Exec "javac" -version 
 stdout:  
 stderr: javac 1.8.0_65

System information:
{ procInfo: 'nativescript/1.7.0',
  platform: 'darwin',
  os: 'Darwin john-thornewills-imac.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.9',
  npmVer: '2.14.9',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.2.1\nBuild version 7C1002\n',
  itunesInstalled: true,
  cocoapodVer: '1.0.0.beta.3',
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.5.4 (Apple Git-61)',
  gradleVer: null,
  javacVersion: '1.8.0_65' }
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'build'.
execFile: /usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb "help"
Looking for project in '/Users/johnt/Dropbox/NativeScript/nextra-workplan4'
Project directory is '/Users/johnt/Dropbox/NativeScript/nextra-workplan4'.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'build|ios'.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/johnt/Dropbox/NativeScript/nextra-workplan4/hooks' ]
BeforeHookName for command prepare is before-prepare
Images from Xcode project
[ 'Default-568h@2x.png',
  'Default-667h@2x.png',
  'Default-736h@3x.png',
  'Default-Landscape-568h@2x.png',
  'Default-Landscape-667h@2x.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Landscape@3x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'placeholder.jpg',
  'receipt.jpg' ]
Current images from App_Resources
[ 'Default-568h@2x.png',
  'Default-667h@2x.png',
  'Default-736h@3x.png',
  'Default-Landscape-568h@2x.png',
  'Default-Landscape-667h@2x.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Landscape@3x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'placeholder.jpg',
  'receipt.jpg' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Successfully prepared plugin nativescript-background-http for ios.
Successfully prepared plugin nativescript-insomnia for ios.
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks in CocoaPods.
Successfully prepared plugin nativescript-iqkeyboardmanager for ios.
Successfully prepared plugin nativescript-screen-orientation for ios.
Successfully prepared plugin nativescript-sqlite for ios.
Successfully prepared plugin tns-core-modules for ios.
Project Podfile content
use_frameworks!
# Begin Podfile - /Users/johnt/Dropbox/NativeScript/nextra-workplan4/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager' 
 # End Podfile 
# Begin Podfile - /Users/johnt/Dropbox/NativeScript/nextra-workplan4/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager' 
 # End Podfile 
# Begin Podfile - /Users/johnt/Dropbox/NativeScript/nextra-workplan4/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager' 
 # End Podfile 

Exec gem which cocoapods 
 stdout: /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods.rb
 
 stderr: 
Exec gem which xcodeproj 
 stdout: /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0.beta.2/lib/xcodeproj.rb
 
 stderr: 
Installing pods...
spawn: sandbox-pod "install"
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.0.beta.6

Analyzing dependencies
[!] The dependency `IQKeyboardManager` is not used in any concrete target.
[Error: Command sandbox-pod failed with exit code 1]
Error: Command sandbox-pod failed with exit code 1
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:236:114
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/helpers.js:215:36
    at PlatformService.descriptor.value [as preparePlatformCore] (/usr/local/lib/node_modules/nativescript/lib/common/helpers.js:182:24)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:186:26
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:256:50
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/commands/build.js:16:73
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:53:55
    - - - - -
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/child-process.js:91:38)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1016:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1
Error: Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:8:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track exception with message 'Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1'.
AnalyticsInstallationID: bcb56572-7a5b-419c-8e8b-4683d8500553
monitor not started
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
Statistics was sent successfully (xhr).
Statistics was sent successfully (xhr).
```
