### ISSUE TITLE
Nativescript-Vue 7 IQPreviousNextView is not defined

### ISSUE THREAD

**Issue by ZhandosKz** [tjvantoll/nativescript-IQKeyboardManager#75]
I'v installed 2 version of this plugin but application on iOS is crushing with error.

How can I solve this problem?

```js
2020-10-17 23:04:12.181181+0300 mobile[18756:477923] * Fatal JavaScript exception - application has been terminated. *
2020-10-17 23:04:12.181273+0300 mobile[18756:477923] NativeScript encountered a fatal error: Uncaught ReferenceError: IQPreviousNextView is not defined
 at 
 createNativeView(file:///app/vendor.js:2:1896867)
 at _setupUI(file:///app/vendor.js:2:117557)
 at (file:///app/vendor.js:2:117816)
 at eachChildView(file:///app/vendor.js:2:468834)
 at eachChildView(file:///app/vendor.js:2:707885)
 at eachChild(file:///app/vendor.js:2:219722)
 at _setupUI(file:///app/vendor.js:2:117800)
 at _addViewCore(file:///app/vendor.js:2:116677)
 at _addView(file:///app/vendor.js:2:116406)
 at UIViewControllerImpl.viewWillAppear(file:///app/vendor.js:2:710709)
 at UINavigationControllerImpl.pushViewControllerAnimated(file:///app/vendor.js:2:244230)
 at _navigateCore(file:///app/vendor.js:2:236714)
 at performNavigation(file:///app/vendor.js:2:227048)
 at _processNextNavigationEntry(file:///app/vendor.js:2:226905)
 at onLoaded(file:///app/vendor.js:2:223991)
 at (file:///app/vendor.js:2:114191)
 at callFunctionWithSuper(file:///app/vendor.js:2:114030)
 at callLoaded(file:///app/vendor.js:2:114138)
 at UINavigationControllerImpl.viewWillAppear(file:///app/vendor.js:2:242814)
(lldb)
```

**Comment by SergioZhydecky** [comment]
You are probably using NS7.

With NS 7 you have to install it with 
`$tns plugin add @nativescript/iqkeyboardmanager`

and use next element reg

```
import { registerElement } from '@nativescript/angular';

registerElement('PreviousNextView', () => require('@nativescript/iqkeyboardmanager').PreviousNextView);
```

**Comment by AdamAtri** [comment]
what if i'm not using angular? just plain-old TS without xml.
